# permissions for end users to edit webservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: webservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: opdemo
    app.kubernetes.io/part-of: opdemo
    app.kubernetes.io/managed-by: kustomize
  name: webservice-editor-role
rules:
- apiGroups:
  - app.enflame.cn
  resources:
  - webservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.enflame.cn
  resources:
  - webservices/status
  verbs:
  - get
